Main Branch Merge
cyberforge1/windows98-fake-os pull request #2
Opened 2024-04-08 06:28 UTC by cyberforge1

Merging main-development branch into main branch.

2024-04-08 07:14 UTC, martynakr requested changes

2024-04-08 07:14 UTC, martynakr commented on js/calculatorApp.js
> +    };
take this out of initializeCalcualtor function

2024-04-08 07:14 UTC, martynakr commented on js/calculatorApp.js
> +    const buttonArr = ['AC', '+/-', '%', '÷', '7', '8', '9', 'x', '4', '5', '6', '-', '1', '2', '3', '+', '0', '.', '='];
Good idea to have a function like this but I would seperate the different things that are happening here:
1. initializeCalculator should create elements for the calculator and add calculator where it should go on the page
2. calculate - just take it out of this function
3. Select all the calcualtor button and add event listeners to all of them outsside of here:
```js
const btns = document.getElementsByClassname("calc-btn")
```

Loop through btns

2024-04-08 07:14 UTC, martynakr commented on js/calculatorApp.js
> +    let createRowAndButtons = () => {
when creating functions, use const so you don't accidentally override to a different data type

2024-04-08 07:14 UTC, martynakr commented on js/calculatorApp.js
> +                newCalculatorRow.appendChild(newButton);
```js
newButton.classList.add('calc-btn')
```

2024-04-08 07:14 UTC, martynakr commented on js/calculatorApp.js
> +                index += 1;
this should be outside of the function that creates calculator elements

2024-04-08 07:14 UTC, martynakr commented on js/calculatorApp.js
> +                return "Cannot divide by zero";
throw errors here so it's more semantically correct

2024-04-08 07:14 UTC, martynakr commented on js/calculatorApp.js
> +document.getElementById('calculatorCard').addEventListener('dblclick', function() {
replace with arrow functions here

2024-04-08 07:14 UTC, martynakr commented on js/notesApp.js
> +            removeButton.onclick = function() {
try and no use onclick but stick to addEventListener

2024-04-08 07:14 UTC, martynakr commented on js/notesApp.js
> +        function addTask() {
add the value of input as a parameter to this function

2024-04-08 07:14 UTC, martynakr commented on js/notesApp.js
> +        const taskInput = document.createElement('input');
```js
const attributes = [{name: "id", value: "taskInput"}]

const createDomElement = (elType, attributes, textContent) => {
    const el = document.createElement(elType)
    attributes.forEach((att) => {
       el.setAttribute(att.name, att.value)
    })
    
    if(textContent) {
       el.textContent = textContent
    }
  return el
}
```

2024-04-08 07:14 UTC, martynakr commented on js/timeModule.js
> +    let formattedTime = hours + ':' + minutes;
Have a look at [toLocaleTimeString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString)

2024-04-08 07:14 UTC, martynakr commented on js/weatherApp.js
> +            <h2>Javascript Weather App</h2>
If you had a general createDOomELement function you could replace this with calling that function

2024-04-08 07:14 UTC, martynakr commented on js/weatherApp.js
> +            const apiKey = '448f568c5483d5b0f66f39e0a3ac8fbc';
don't expose this on github, create a .env file and import from there, also add that file to .gitignore

2024-04-08 07:14 UTC, martynakr commented on js/weatherApp.js
> +            }
this should be its own function 
```js
const getLatLong = (city) => {
 const geoResponse = await fetch(`http://api.openweathermap.org/geo/1.0/direct?q=${city}&limit=1&appid=${apiKey}`;
  const geoData = await geoResponse.json();
  if (geoData.length < 0) {
     throw new Error("")
     }
      
 return geoData;

}
```

2024-04-08 07:14 UTC, martynakr commented on js/weatherApp.js
> +            }
```js
const getWeatherData = (geoData) => {
   const { lat, lon } = geoData[0];
   const weatherUrl = `https://api.openweathermap.org/data/2.5/weather?lat=${lat}&lon=${lon}&appid=${apiKey}`;

       const weatherResponse = await fetch(weatherUrl);
       const weatherData = await weatherResponse.json();
       return weatherData;
}
```

2024-04-08 07:14 UTC, martynakr commented on js/weatherApp.js
> +            }
```js
try {
   const latLong = await getLatLong(input.value)
   const weatherData = await getWeatherData(latLong)
   someFunctionThtaCreatesWetherInfoAndAddsToDom(weatherData)
} catch(e) {
    alter("")
    return
}


```

2024-04-08 07:14 UTC, martynakr commented on index.html
> +
Remove all the long spaces

2024-04-10 03:56 UTC, merged

2024-05-29 03:31 UTC, cyberforge1 reviewed
These suggestions have been reviewed and integrated into main branch.